// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM-F-I8SP-Rml_seoWD3HWiGXUD_N_3lA',
    appId: '1:658468262790:web:8b9aca33fb8050f37c9207',
    messagingSenderId: '658468262790',
    projectId: 'medispenser-c25fb',
    authDomain: 'medispenser-c25fb.firebaseapp.com',
    databaseURL: 'https://medispenser-c25fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medispenser-c25fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7I3A5dBwiH0-q6FBqHGof23pXWolNoJU',
    appId: '1:658468262790:android:d93167728c9ed0417c9207',
    messagingSenderId: '658468262790',
    projectId: 'medispenser-c25fb',
    databaseURL: 'https://medispenser-c25fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medispenser-c25fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeQ6cE381tbVkbHkVOmkPLy_axOTJhXyw',
    appId: '1:658468262790:ios:0faedcfa1e1827817c9207',
    messagingSenderId: '658468262790',
    projectId: 'medispenser-c25fb',
    databaseURL: 'https://medispenser-c25fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medispenser-c25fb.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeQ6cE381tbVkbHkVOmkPLy_axOTJhXyw',
    appId: '1:658468262790:ios:b53c739e91a81f937c9207',
    messagingSenderId: '658468262790',
    projectId: 'medispenser-c25fb',
    databaseURL: 'https://medispenser-c25fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medispenser-c25fb.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
